version: '3.8'

services:
  web:
    build: .
    image: artklk12/wunderlist:latest
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A mysite worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis

  redis:
    image: redis:latest
