# Generated by Django 4.0.3 on 2022-04-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_testtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtask',
            options={},
        ),
    ]
