# Generated by Django 4.0.3 on 2022-04-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_testtask_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtask',
            options={'ordering': ['id']},
        ),
    ]
