# Generated by Django 4.0.3 on 2022-04-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_testtask_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='title',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.category', verbose_name='Category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
