# Generated by Django 4.0.3 on 2022-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_testtask_title_testcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='content',
            field=models.TextField(max_length=300, null=True, verbose_name='Content'),
        ),
        migrations.DeleteModel(
            name='TestCategory',
        ),
    ]
