# Generated by Django 4.0.3 on 2022-06-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasks_content_delete_testcategory'),
    ]

    operations = [
    ]
