# Generated by Django 4.0.3 on 2022-06-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20220616_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Content'),
        ),
    ]
