# Generated by Django 4.0.3 on 2022-06-22 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_alter_tasks_category_alter_tasks_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testtask',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
